### ISSUE TITLE
Rileylink Error: RadioDisconnectPrematurely

### ISSUE THREAD

**Issue by yumtime** [winemug/OmniCore#10]
Whenever I press "update" or try to activate a pod, I get this error:

![Screenshot_20190923-134309](https://user-images.githubusercontent.com/37127272/65449490-1a5ec080-de09-11e9-9a6a-8348ff450487.png)

I have a new rileylink, and I am using the Omnicore 1.0.0.702.
Phone is a Pixel 3 running Android 10

I can get my phone connected, and the green LED on, but I have yet been able to successfully activate a pod with Rileylink and Omnicore. 

This seems like the same issue which was addressed before (issue #3), however when I follow those steps, it is still not working for me. 

Any ideas?

**Comment by vanelsberg** [comment]
Could be an issue related to your phone hardware. (Not all phones have been tested).
Join the OmniCore Slack channel. You'll find many OmniCore users that are happy to help you. It's invites only. Add your e-mail to Github?

**Comment by yumtime** [comment]
It's been added. Thank you!

**Comment by miguelleon94** [comment]
Try using Jun28 builds for AAPS and OC and see if you have better luck.
OC:  cdecf6b8476ec8aef9a7ef6165592a1237eb3d8c
AAPS:  01b94ba6c8cac4e0e980d089e7dd28ee2cf507ca

**Comment by yumtime** [comment]
@miguelleon94 Thanks. I'm pretty new to github, git and any sort of development in general. I've been using the latest alpha .apk  provided, so unfortunately I'm not really sure what I would have to do with the codes you recommended. sorry :/

**Comment by miguelleon94** [comment]
post an email address, so we can send you a Slack invite.  We can help you better there.

**Comment by yumtime** [comment]
done, it should be in my profile
