### ISSUE TITLE
No communication between omnicore and AAPS

### ISSUE THREAD

**Issue by auxlife** [winemug/OmniCore#11]
Omnicore was able to start and activated a pod, it is connected to the pod/RL. However AAPS keeps alternating between "Connecting for Xs" and Pump suspended. It appears that AAPS is unable to connect/communicate with omnicore. "Accept AndroidAPS commands" is enabled in the settings page of OmniCore.

**Comment by vanelsberg** [comment]
Omnicore and AAPS  ersions must match. Did you build Omnicore-AAPS from one of the following commits?

if you install July6 OC from appcenter download, then you should use AAPS commit `babca6e`

if you use Jun28 OC build then you need AAPS commit `01b94ba`

**Comment by auxlife** [comment]
Thank you, I thought i had pulled the correct commit; but somehow i reset back to head before building.
