### ISSUE TITLE
RileyLink Communication Errror

### ISSUE THREAD

**Issue by FischBrei** [winemug/OmniCore#3]
Mobile Phone is connected via bluetooth with the RileyLink (green LED3 on).
Pod activation fails. OmniCore Conversations shows first  "Error communicating with RileyLink (retry: #3)" and then "Message exchange failed: RadioDisconnectPrematurley"

RileyLink is new (order from July 2019), so it should have the latest firmware. OmniCore is Version 1.0.0.702 build with VisualStudio & Release Version.
When trying the test => Radio connection test, the app closes and reopens. 

There are little no no blue flashing on the Rileylink.

Screenshots:
![Screenshot_20190711-230253](https://user-images.githubusercontent.com/36920852/61085530-c4e15d00-a430-11e9-9589-3c468a44f108.jpg)
![Screenshot_20190711-230301](https://user-images.githubusercontent.com/36920852/61085535-c7dc4d80-a430-11e9-8e0a-cb7fe45d3b1d.jpg)

**Comment by smokkelaar** [comment]
I have exact the same issue,
In nRF i don't see any communication going on to the bluetooth device, like the porgram cannot find the rileylink at all.
Device: Samsung S7
android 8.0.0
board: universal8890

bluethooth support propperties:
BLE : Yes
Native HID: Yes
Lollipop scanner API: yes
offloaded filtering: yes
offloaded scan batching: yes
peripheral mode: yes
multiple advertisement: yes
High speed (PHY 2M): No
Long rang (PHY Coded): No
Periodic advertisement: No
Extended advertisement: No
Maximum advertising data length: 31

**Comment by vanelsberg** [comment]
**This is a know issue for the current OmniCore alpha version 1.0.702**

To work around try the following:
1. Force shutdown/Exit Omnicore using the menu option Test -> Exit.
2. Reopen OmniCore (it may autostart at this point).
3. Toggle Bluetooth on/off (Green LED on RL goes off).
4a. Press the "UPDATE" button.
4b. If you are trying to activate, see below.
5. Green LED on RL should go on, Conversations should say "Search for RileyLink...".
Wait some. OmniCore should report "Finished" + "Result Received".
**If not, retry from (1)**

_Note: You may have to close/reopen OmniCore (the normal way) to see recent progress as the screens do not always refresh properly.

(4b) When trying to activate a new Pod:
Do as above, but after hitting "UPDATE" the first time, try the "Activate" button and watch conversations. At some point you will see it connecting to the Pod and start communicating with it. Please be patient.
If not - retry "ACTIVATE". Do not forget to close/reopen OmniCore to refresh the screen or button states. You may need to repeat the above for about 3 times. If it does not start communicating by then, retry the procedure from (1)

**Comment by FischBrei** [comment]
@vanelsberg thank you, that fixed the issue for me :- )
